### ISSUE TITLE
手机安装Actinium需要设置Socks5代理吗？

### ISSUE THREAD

**Issue by lucaskeen** [wangyi2005/v2ray#10]
@wangyi2005 我的手机没有代理协议设置的选项，只能设置地址、端口和不用代理的网站。用楼主的Actinium配置文件连不通。我看了配置文件里的代理协议是Socks5，需要在手机上安装设置Socks5代理协议吗？请大神帮忙看一下

**Comment by wangyi2005** [comment]
Actinium 是VPN模式，不需要设置。

**Comment by lucaskeen** [comment]
@wangyi2005 我设置好config.json，打开后Google、油管一直连不通，但Actinium本身好像不停的传输数据，主要是上传，1个多小时上传了40M，不知道在干什么？

![screenshot_2017-11-06-22-22-42-80](https://user-images.githubusercontent.com/25589008/32445960-4ebf44e6-c342-11e7-94d3-81ec4aa9272d.png)

大神能帮我看下怎么回事吗？

**Comment by wangyi2005** [comment]
看看服务端的log，客户端没有收到数据。正常情况下，下载量应该是上传量的10倍。

**Comment by lucaskeen** [comment]
@wangyi2005 Actinium在一个ISP上通了。另一个ISP，PC端V2Ray-core能通，手机上Actinium不通，用的都是同一个config.json，不知道为什么 ......
