### ISSUE TITLE
每次Docker版本升级，OpenShift服务器端能自动更新吗?

### ISSUE THREAD

**Issue by lucaskeen** [wangyi2005/v2ray#11]
@wangyi2005 如果不能自动更新，如何手动更新呢？

**Comment by lucaskeen** [comment]
@wangyi2005 是这个吗

![image](https://user-images.githubusercontent.com/25589008/32695415-fb96b562-c795-11e7-975b-ab0cad15ae59.png)

**Comment by wangyi2005** [comment]
1、参考openshift文档，docker push。
2、重新部署。
