### ISSUE TITLE
在OpenShift部署v2ray出现错误提示，是哪里出了问题

### ISSUE THREAD

**Issue by 2018song** [wangyi2005/v2ray#20]
Connecting to github.com (192.30.255.112:80)
Connecting to github.com (192.30.255.113:443)
wget: server returned error: HTTP/1.1 404 Not Found
unzip: can't open v2ray.zip[.zip]
mv: can't rename '/v2ray/v2ray-v-linux-64/v2ray': No such file or directory
mv: can't rename '/v2ray/v2ray-v-linux-64/v2ctl': No such file or directory
mv: can't rename '/v2ray/v2ray-v-linux-64/geoip.dat': No such file or directory
mv: can't rename '/v2ray/v2ray-v-linux-64/geosite.dat': No such file or directory
chmod: v2ray: No such file or directory
chmod: v2ctl: No such file or directory
/entrypoint.sh: line 18: ./v2ray: not found﻿
 

求大神更新解决

**Comment by disuwww** [comment]
| Connecting to github.com (192.30.253.112:80)
-- | --
  | Connecting to github.com (192.30.253.113:443)
  | wget: server returned error: HTTP/1.1 404 Not Found
  | unzip: can't open v2ray.zip[.zip]
  | mv: can't rename '/v2ray/v2ray-v-linux-64/v2ray': No such file or directory
  | mv: can't rename '/v2ray/v2ray-v-linux-64/v2ctl': No such file or directory
  | mv: can't rename '/v2ray/v2ray-v-linux-64/geoip.dat': No such file or directory
  | mv: can't rename '/v2ray/v2ray-v-linux-64/geosite.dat': No such file or directory
  | chmod: v2ray: No such file or directory
  | chmod: v2ctl: No such file or directory
  | /entrypoint.sh: line 18: ./v2ray: not found

me too

**Comment by wangyi2005** [comment]
require  two environment variables
VER  --->v2ray version
UUID--->https://www.uuidgenerator.net/

**Comment by 2018song** [comment]
I am new here，and would you please tell me what changes need to be made in the dockerfile or other file? Or would you please update these files?

**Comment by wangyi2005** [comment]
openshift：
![image](https://user-images.githubusercontent.com/18438595/46900881-488b0f00-cedc-11e8-8fa3-c2a458591227.png)

**Comment by 2018song** [comment]
Thanks a lot!
