### ISSUE TITLE
报错了 没关系吗？

### ISSUE THREAD

**Issue by daiaji** [wangyi2005/v2ray#6]
```
--> Scaling v2ray-1 to 1
--> Waiting up to 10m0s for pods in rc v2ray-1 to become ready
W1007 16:05:19.663900       1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 189123980 (189131318)
error: update acceptor rejected v2ray-1: pods for rc "v2ray-1" took longer than 600 seconds to become ready
```
还有就是疯狂的部署不了

**Comment by wangyi2005** [comment]
create a project-->deploy image--->CONFIG_JSON--->CERT_PEM---->KEY_PEM--->create route---->DONE

**Comment by daiaji** [comment]
@wangyi2005 我没有CERT_PEM KEY_PEM 不用导入吧？
`Error syncing pod`
现在基本上都这样了

**Comment by wangyi2005** [comment]
openshift 部署这么难吗，有个截图就好了！

**Comment by daiaji** [comment]
@wangyi2005 我似乎部署成功过一次
但是没有create route 没地址 我以为部署失败了 重新部署去了
然后就一直这样了

**Comment by wangyi2005** [comment]
我的建议是删除porject，重新部署。

**Comment by daiaji** [comment]
@wangyi2005 
![default](https://user-images.githubusercontent.com/25875791/31386299-da41b846-adf8-11e7-8a6d-4914956d5f7d.png)
我的脸是真的黑啊

**Comment by wangyi2005** [comment]
https://docs.openshift.com/online/architecture/networking/port_forwarding.html
