### ISSUE TITLE
大神能给看看吗：部署 V2Ray 2.45 永远的 Error syncing pod ...

### ISSUE THREAD

**Issue by lucaskeen** [wangyi2005/v2ray#7]
@wangyi2005 

![openshift_01](https://user-images.githubusercontent.com/25589008/32313628-d7605e50-bfde-11e7-8517-b6931a924848.png)

![openshift_02](https://user-images.githubusercontent.com/25589008/32313629-d8070e4e-bfde-11e7-8f0c-b5eb75816f47.png)

![openshift_03](https://user-images.githubusercontent.com/25589008/32313630-d85c5566-bfde-11e7-9824-686dc0c379cf.png)

![openshift_04](https://user-images.githubusercontent.com/25589008/32313645-ec6f76a0-bfde-11e7-9253-5efae1669e03.png)

![openshift_05](https://user-images.githubusercontent.com/25589008/32313655-f561bf2a-bfde-11e7-9d1d-8088ad215c8a.png)

![openshift_06](https://user-images.githubusercontent.com/25589008/32313632-d92cc750-bfde-11e7-961c-9161b7166a71.png)

**Comment by wangyi2005** [comment]
openshift自身问题，每个节点都可以试试，看看能不能部署上。
