### ISSUE TITLE
openshift 部署 V2Ray  Websocket 服务端成功，客户端怎么弄，谢谢大神解惑！

### ISSUE THREAD

**Issue by siaqib** [wangyi2005/v2ray#8]
openshift 部署 V2Ray  Websocket 服务端，输入ers-sig.7e14.starter-us-west-2.openshiftapps.com，提示
Bad Request。应该成功了。下载了楼主的v2ray-2.45，将，
{
  "log": {
    "loglevel": "warning"
  },
   "inbound": {
    "port": 8080,
    "protocol": "http",
    "listen": "127.0.0.1",
	"settings": {
    }
  },
  "inboundDetour": [],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "ers-sig..7e14.starter-us-west-2.openshiftapps.com", 
          "port": 443, 
          "users": [
            {
              "id": "#######################",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    },
	"streamSettings": {
      "network": "ws",
	  "security": "tls",
	  "tlsSettings": {
        "allowInsecure": true
	  }
    },
	"mux": {
        "enabled": true,
        "concurrency": 8
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}  这些复制到v2ray-2.45 config.json文件里，没有启动程序，我是win10系统，请教老大解惑，谢谢！

**Comment by wangyi2005** [comment]
这里没有客户端程序，客户端在
 https://github.com/v2ray/v2ray-core/releases/tag/v2.45

**Comment by siaqib** [comment]
@wangyi2005 非常感谢！可以用了。还有个问题，麻烦一起解答，谢谢。
openshift 部署 V2Ray  sniproxy 用
"outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "sniproxy ip-1", 
          "port": 443, 
          "users": [
            {
              "id": "######-######-########",
              "alterId": 64,
              "security": "none"
            }
          ]
        },
	{
          "address": "sniproxy ip-2", 
          "port": 443, 
          "users": [
            {
              "id": "#####-######-######",
              "alterId": 64,
              "security": "none"
            }
          ]
        },
	{
          "address": "sniproxy ip-3", 
          "port": 443, 
          "users": [
            {
              "id": "#####-######-######",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    },
   "streamSettings": {
          "network": "tcp",
	  "security": "tls",
	  "tlsSettings": {
	    "serverName": "########.7e14.starter-us-west-2.openshiftapps.com",
            "allowInsecure": true
	  },
	  "tcpSettings": {
	    "header": {
                "type": "http",
               "request": {
                   "version": "1.1",
                   "method": "GET",
                   "path": ["/"],
                   "headers": {
                   "Host": ["www.office.com", "www.windows.com","www.apple.com"],
                   "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
				"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
              "Transfer-Encoding": ["chunked"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
	    }
	  }	
    },
    "mux": {
        "enabled": true,
        "concurrency": 8
    }
  } 此文件做服务端，https 模式：Openshift3 route：passthrough，v2ray：http伪装+tls+vmess（不加密）用goproxy生成的ecc证书，不用自签证书可否。

**Comment by wangyi2005** [comment]
如果"allowInsecure": true，啥证书都可以。

**Comment by lucaskeen** [comment]
请问 @wangyi2005 @siaqib 

我也是在Openshift配置的Websocket模式的服务端，应该成功了

![openshift_deploy_07](https://user-images.githubusercontent.com/25589008/32368609-47e8fc9e-c0c1-11e7-8384-54f90d053cde.png)

然后下载v2ray/v2ray-core的v2ray-windows-32.zip解压，拷贝楼主的Websocket模式pc端的config.json，再运行v2ray.exe，不成功，报错：

$ v2ray.exe
V2Ray v2.45 (One for all) 20171029
An unified platform for anti-censorship.
2017/11/03 17:51:00 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.1:8080
2017/11/03 17:51:00 [Info]Transport|Internet|TCP: listening TCP on 127.0.0.1:8080
2017/11/03 17:51:00 [Warning]Core: V2Ray started
2017/11/03 17:51:32 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://********.7e14.starter-us-west-2.openshiftapps.com/): 503 Service Unavailable > websocket: bad handshake] > Retry: all retry attempts failed

楼主和楼上两位能否帮我看一下，谢谢！

**Comment by siaqib** [comment]
@lucaskeen 你输入布置的ig.7e14.starter-us-west-2.openshiftapps.com 域名试试
 提示是Bad Request 确定成功部署。
2，"id": "b7cdcdee-c087-11e7-abc4-cec278b6b50a ", 应该和客户端保持一样

**Comment by siaqib** [comment]
@wangyi2005 谢谢耐心解答，用goproxy生成的ecc证书需要导入吗，怎样导入。

**Comment by wangyi2005** [comment]
websocket模式不需要证书

**Comment by wangyi2005** [comment]
@lucaskeen openshift要 配置secure route：edge。

**Comment by siaqib** [comment]
@wangyi2005 我说的是openshift 部署 V2Ray sniproxy 的https 模式，用goproxy生成的证书
是否需要导入，不清楚。谢谢解答！

**Comment by wangyi2005** [comment]
![image](https://user-images.githubusercontent.com/18438595/32374161-7faf3114-c0d7-11e7-8b4a-5df4317d92ef.png)
CERT_PEM（证书）、KEY_PEM（私钥）

**Comment by lucaskeen** [comment]
谢谢 @wangyi2005 @siaqib 
我的route也一样部署成功，id一致。
配置secure route：edge后就可以用了！-:)

**Comment by lucaskeen** [comment]
@wangyi2005 @siaqib 有几个问题请教一下 

1. Sniproxy的Http方式：

"outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "sniproxy ip-1", 

"address": "sniproxy ip-1", 可以是"##############.7e14.starter-us-west-2.openshiftapps.com"吗?

能把完整的PC端配置文件贴出来吗？

2. Websocket模式的PC端配置文件：

      "vnext": [
        {
          "address": "##############.7e14.starter-us-west-2.openshiftapps.com", 
          "port": 443, 
          "users": [
            {
              "id": "#######################",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]

可以设置多个实现负载均衡吗？

3. Https模式：

CERT_PEM， 证书，SAN：*.7e14.starter-us-west-2.openshiftapps.com
KEY_PEM ， 私钥 EC or RSA

自定义证书和私钥的签发和生成，能推荐个方便的工具或链接吗？

谢谢！

**Comment by wangyi2005** [comment]
1、sniproxy ip-1 是sniproxy 的IP地址，不是openshift 服务端地址。只要修改outbound，其他配置是一样的。
2、关于负载平衡是指 多个 sniproxy 指向 一个openshift 服务端地址，建议用1-2个就行了。
3、关于证书，可以用goproxy生成ecc证书，或者用openssl、XCA。

**Comment by siaqib** [comment]
@wangyi2005 谢谢说明。老大这个openshift 部署 V2Ray之 sniproxy  https模式
"outbound": {
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "sniproxy ip-1",
"port": 443,
"users": [
{
"id": "######-######-########",
"alterId": 64,
"security": "none"
}
]
},
{
"address": "sniproxy ip-2",
"port": 443,
"users": [
{
"id": "#####-######-######",
"alterId": 64,
"security": "none"
}
]
},
{
"address": "sniproxy ip-3",
"port": 443,
"users": [
{
"id": "#####-######-######",
"alterId": 64,
"security": "none"
}
]
}
]
},
"streamSettings": {
"network": "tcp",
"security": "tls",
"tlsSettings": {
"serverName": "########.7e14.starter-us-west-2.openshiftapps.com",
"allowInsecure": true
},
"tcpSettings": {
"header": {
"type": "http",
"request": {
"version": "1.1",
"method": "GET",
"path": ["/"],
"headers": {
"Host": ["www.office.com", "www.windows.com","www.apple.com"],
"User-Agent": [
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
],
"Accept-Encoding": ["gzip, deflate"],
"Connection": ["keep-alive"],
"Pragma": "no-cache"
}
},
"response": {
"version": "1.1",
"status": "200",
"reason": "OK",
"headers": {
"Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
"Transfer-Encoding": ["chunked"],
"Connection": ["keep-alive"],
"Pragma": "no-cache"
}
}
}
}
},
"mux": {
"enabled": true,
"concurrency": 8
} 此配置是作为服务端还是客户端使用，把我看晕了，不好意思添麻烦了。

**Comment by wangyi2005** [comment]
客户端

**Comment by siaqib** [comment]
@wangyi2005 非常感谢！

**Comment by lucaskeen** [comment]
@wangyi2005 

想尝试一下部署Https模式，服务端好像成功了

![pods](https://user-images.githubusercontent.com/25589008/32404318-77bd06d2-c188-11e7-92e2-bc23b70d26a7.png)

但点击 https://××××××××.193b.starter-ca-central-1.openshiftapps.com/ 就显示

502 Bad Gateway
The server returned an invalid or incomplete response.

不知道是否正常？

Route设置：

https://××××××.193b.starter-ca-central-1.openshiftapps.com 

 Exposed on router 'router' 10 minutes ago

Details

Path: none
Service: v2ray
Target Port: 8080-tcp
This target port will route to Service Port 8080 → Container Port 8080 (TCP).

TLS Settings

Termination Type: Edge
Insecure Traffic: None
Certificate: none
Key: none
CA Certificate: none
Destination CA Cert: none

不知道还需要设置什么？

Https模式PC端的config.json：
127.0.0.1的端口没用8080，随便用了个别的，因为都设置在SwitchyOmega里统一管理，避免和V2Ray Websocket模式客户端起冲突，不知有没有关系？但V2Ray-Websocket + SwitchyOmega是没问题的 ...... address, serverName 和 id 都改成了对应的值，不知道PC端config.json里还有其他什么地方需要改或者特别设置的?

客户端运行 v2ray.exe，结果如下：

V2Ray v2.45 (One for all) 20171029
An unified platform for anti-censorship.
2017/11/04 17:05:37 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.
1:8080
2017/11/04 17:05:37 [Warning]Core: V2Ray started
2017/11/04 17:05:58 [Warning]failed to handler mux client connection > Proxy|VMe
ss|Outbound: connection ends > EOF
2017/11/04 17:06:02 [Warning]failed to handler mux client connection > Proxy|VMe
ss|Outbound: connection ends > EOF
2017/11/04 17:06:06 [Warning]failed to handler mux client connection > Proxy|VMe
ss|Outbound: connection ends > EOF
2017/11/04 17:06:10 [Warning]failed to handler mux client connection > Proxy|VMe
ss|Outbound: connection ends > EOF

Youtube、Google一律不通，请大神在帮忙看一下是什么问题，多谢！

**Comment by siaqib** [comment]
@lucaskeen 
secure route：passthrough
重新布置

**Comment by siaqib** [comment]
@wangyi2005 @lucaskeen  sorry,点错了，把贴挂了。请继续

**Comment by lucaskeen** [comment]
@wangyi2005 多谢，果然Https也通了！
@siaqib 还是挂了，能再打开吗？

**Comment by siaqib** [comment]
@lucaskeen 好像姐不了，我们应该谢谢@wangyi2005 大神！
你的证书文件导入的图片发一个看看，另外你用了sni ip没有

**Comment by lucaskeen** [comment]
@siaqib 证书和私钥就按照 @wangyi2005 的方法导入：

![image](https://user-images.githubusercontent.com/25589008/32405262-0069f116-c19d-11e7-8518-0643b291f2a6.png)

我还没用sni ip，怎么获取 sni ip 啊

**Comment by siaqib** [comment]
@lucaskeen sni ip,不知道怎么获取，明天我搜索看看。你的config.json服务端改成一行的
配置文件发个我试试，自己改的文件就是部署不成功。我怀疑是Notepad++的问题。

**Comment by lucaskeen** [comment]
@siaqib 

https:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "963790d4-bc86-11e7-abc4-cec278b6b50a",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "tcp",\n	  "security": "tls",\n	  "tlsSettings": {\n        "serverName": "v2ray-lucashood-v2ray-https-docker-wangyi2005.193b.starter-ca-central-1.openshiftapps.com",\n        "certificates": [\n        {\n          "certificateFile": "/v2raybin/cert.pem",\n          "keyFile": "/v2raybin/key.pem"\n        }\n        ]\n	  },\n	  "tcpSettings": {\n	    "header": {\n          "type": "http",\n          "request": {\n            "version": "1.1",\n            "method": "GET",\n            "path": ["/"],\n            "headers": {\n              "Host": ["www.office.com", "www.windows.com","www.apple.com"],\n              "User-Agent": [\n                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",\n				"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"\n              ],\n              "Accept-Encoding": ["gzip, deflate"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          },\n          "response": {\n            "version": "1.1",\n            "status": "200",\n            "reason": "OK",\n            "headers": {\n              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],\n              "Transfer-Encoding": ["chunked"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          }\n	    }\n	  }\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

websocket:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "963790d4-bc86-11e7-abc4-cec278b6b50a",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "ws"\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

**Comment by lucaskeen** [comment]
@siaqib 

websocket:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "**************",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "ws"\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

https:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "**************",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "tcp",\n	  "security": "tls",\n	  "tlsSettings": {\n        "serverName": "**************.193b.starter-ca-central-1.openshiftapps.com",\n        "certificates": [\n        {\n          "certificateFile": "/v2raybin/cert.pem",\n          "keyFile": "/v2raybin/key.pem"\n        }\n        ]\n	  },\n	  "tcpSettings": {\n	    "header": {\n          "type": "http",\n          "request": {\n            "version": "1.1",\n            "method": "GET",\n            "path": ["/"],\n            "headers": {\n              "Host": ["www.office.com", "www.windows.com","www.apple.com"],\n              "User-Agent": [\n                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",\n				"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"\n              ],\n              "Accept-Encoding": ["gzip, deflate"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          },\n          "response": {\n            "version": "1.1",\n            "status": "200",\n            "reason": "OK",\n            "headers": {\n              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],\n              "Transfer-Encoding": ["chunked"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          }\n	    }\n	  }\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

**Comment by lucaskeen** [comment]
@siaqib 

https:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "###########",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "tcp",\n	  "security": "tls",\n	  "tlsSettings": {\n        "serverName": "###########.193b.starter-ca-central-1.openshiftapps.com",\n        "certificates": [\n        {\n          "certificateFile": "/v2raybin/cert.pem",\n          "keyFile": "/v2raybin/key.pem"\n        }\n        ]\n	  },\n	  "tcpSettings": {\n	    "header": {\n          "type": "http",\n          "request": {\n            "version": "1.1",\n            "method": "GET",\n            "path": ["/"],\n            "headers": {\n              "Host": ["www.office.com", "www.windows.com","www.apple.com"],\n              "User-Agent": [\n                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",\n				"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"\n              ],\n              "Accept-Encoding": ["gzip, deflate"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          },\n          "response": {\n            "version": "1.1",\n            "status": "200",\n            "reason": "OK",\n            "headers": {\n              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],\n              "Transfer-Encoding": ["chunked"],\n              "Connection": ["keep-alive"],\n              "Pragma": "no-cache"\n            }\n          }\n	    }\n	  }\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

websocket:

{\n  "log": {\n    "loglevel": "warning"\n  },\n  "inbound": {\n    "protocol": "vmess",\n    "port": 8080,\n    "settings": {\n      "clients": [\n        {\n          "id": "###########",\n          "alterId": 64,\n          "security": "none"\n        }\n      ]\n    },\n    "streamSettings": {\n      "network": "ws"\n    }\n  },\n  "inboundDetour": [],\n  "outbound": {\n    "protocol": "freedom",\n   "settings": {}\n  }\n}

**Comment by siaqib** [comment]
@lucaskeen 你用，
"outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "219.76.4.78", 
          "port": 443, 
          "users": [
            {
              "id": "######-######-########",
              "alterId": 64,
              "security": "none"
            }
          ]
        },
	{
          "address": "119.28.98.231", 
          "port": 443, 
          "users": [
            {
              "id": "#####-######-######",
              "alterId": 64,
              "security": "none"
            }
          ]
        },
	{
          "address": "sniproxy ip-3", 
          "port": 443, 
          "users": [
            {
              "id": "#####-######-######",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    },
   "streamSettings": {
          "network": "tcp",
	  "security": "tls",
	  "tlsSettings": {
	    "serverName": "########.7e14.starter-us-west-2.openshiftapps.com",
            "allowInsecure": true
	  },
	  "tcpSettings": {
	    "header": {
                "type": "http",
               "request": {
                   "version": "1.1",
                   "method": "GET",
                   "path": ["/"],
                   "headers": {
                   "Host": ["www.office.com", "www.windows.com","www.apple.com"],
                   "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
				"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
              "Transfer-Encoding": ["chunked"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
	    }
	  }	
    },
    "mux": {
        "enabled": true,
        "concurrency": 8
    }
  }
此配置做客户端使用，端口443.试试sni加速。

**Comment by lucaskeen** [comment]
@siaqib 谢谢。试了10分钟，效果不是很明显，油管720P速度在1-3M之间，之前单独Https或WS模式可以达到4-9M。你的2个Sni IP是哪里的，国内的还是国外的？

**Comment by lucaskeen** [comment]
@siaqib @wangyi2005 
楼上这个是完整的客户端配置吗？不需要 "inbound"部分吗？

   "inbound": {
    "port": 8098,
    "protocol": "http",
    "listen": "127.0.0.1",
	"settings": {
    }
  },
  "inboundDetour": [],

**Comment by siaqib** [comment]
@lucaskeen 貌似sni ip 背墙限制了。你https 模式布置成功，输入域名显示是什么，
我想确定一下

**Comment by lucaskeen** [comment]
@siaqib 比如"###########.193b.starter-ca-central-1.openshiftapps.com", 其实就是你 Create Route 后生成的链接，下面红框里这个，去掉前面的 “https://"：

![image](https://user-images.githubusercontent.com/25589008/32428108-1aedf4ca-c2ff-11e7-9757-e13235dbe3cb.png)

**Comment by siaqib** [comment]
@lucaskeen 谢谢帮忙贴图。服务端好了，sni加速的客户端你改动没有，我这没有搞好，
麻烦贴个配置看看

**Comment by lucaskeen** [comment]
@siaqib sni 没再试了，没有ip

**Comment by siaqib** [comment]
@lucaskeen 里面有sni ip,下载后看说明文件

https://raw.githubusercontent.com/dou4cc/resource/master/fq.7z
